In [42]:
import pandas as pd

df = pd.read_csv("weather_data.csv", parse_dates=["day"])
df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [7]:
type(df.day[0])

pandas.Timestamp

In [43]:
df.set_index(df.day, inplace=True)

In [10]:
df

                  day  temperature  windspeed   event
day
2017-01-01 2017-01-01         32.0        6.0    Rain
2017-01-04 2017-01-04          NaN        9.0   Sunny
2017-01-05 2017-01-05         28.0        NaN    Snow
2017-01-06 2017-01-06          NaN        7.0     NaN
2017-01-07 2017-01-07         32.0        NaN    Rain
2017-01-08 2017-01-08          NaN        NaN   Sunny
2017-01-09 2017-01-09          NaN        NaN     NaN
2017-01-10 2017-01-10         34.1        8.1  Cloudy
2017-01-11 2017-01-11         40.0       12.0   Sunny

In [11]:
df_zero = df.fillna(0)
df_zero

                  day  temperature  windspeed   event
day
2017-01-01 2017-01-01         32.0        6.0    Rain
2017-01-04 2017-01-04          0.0        9.0   Sunny
2017-01-05 2017-01-05         28.0        0.0    Snow
2017-01-06 2017-01-06          0.0        7.0       0
2017-01-07 2017-01-07         32.0        0.0    Rain
2017-01-08 2017-01-08          0.0        0.0   Sunny
2017-01-09 2017-01-09          0.0        0.0       0
2017-01-10 2017-01-10         34.1        8.1  Cloudy
2017-01-11 2017-01-11         40.0       12.0   Sunny

In [16]:
df_stats = df.fillna({
    'temperature': df.temperature.mean(),
    'windspeed': df.windspeed.mean(),
    'event': 'No Event'
})
df_stats

         day  temperature  windspeed     event
0 2017-01-01        32.00       6.00      Rain
1 2017-01-04        33.22       9.00     Sunny
2 2017-01-05        28.00       8.42      Snow
3 2017-01-06        33.22       7.00  No Event
4 2017-01-07        32.00       8.42      Rain
5 2017-01-08        33.22       8.42     Sunny
6 2017-01-09        33.22       8.42  No Event
7 2017-01-10        34.10       8.10    Cloudy
8 2017-01-11        40.00      12.00     Sunny

In [19]:
df

                  day  temperature  windspeed   event
day
2017-01-01 2017-01-01         32.0        6.0    Rain
2017-01-04 2017-01-04          NaN        9.0   Sunny
2017-01-05 2017-01-05         28.0        NaN    Snow
2017-01-06 2017-01-06          NaN        7.0     NaN
2017-01-07 2017-01-07         32.0        NaN    Rain
2017-01-08 2017-01-08          NaN        NaN   Sunny
2017-01-09 2017-01-09          NaN        NaN     NaN
2017-01-10 2017-01-10         34.1        8.1  Cloudy
2017-01-11 2017-01-11         40.0       12.0   Sunny

In [23]:
df.ffill()

                  day  temperature  windspeed   event
day
2017-01-01 2017-01-01         32.0        6.0    Rain
2017-01-04 2017-01-04         32.0        9.0   Sunny
2017-01-05 2017-01-05         28.0        9.0    Snow
2017-01-06 2017-01-06         28.0        7.0    Snow
2017-01-07 2017-01-07         32.0        7.0    Rain
2017-01-08 2017-01-08         32.0        7.0   Sunny
2017-01-09 2017-01-09         32.0        7.0   Sunny
2017-01-10 2017-01-10         34.1        8.1  Cloudy
2017-01-11 2017-01-11         40.0       12.0   Sunny

In [24]:
df.bfill()

                  day  temperature  windspeed   event
day
2017-01-01 2017-01-01         32.0        6.0    Rain
2017-01-04 2017-01-04         28.0        9.0   Sunny
2017-01-05 2017-01-05         28.0        7.0    Snow
2017-01-06 2017-01-06         32.0        7.0    Rain
2017-01-07 2017-01-07         32.0        8.1    Rain
2017-01-08 2017-01-08         34.1        8.1   Sunny
2017-01-09 2017-01-09         34.1        8.1  Cloudy
2017-01-10 2017-01-10         34.1        8.1  Cloudy
2017-01-11 2017-01-11         40.0       12.0   Sunny

In [25]:
df

                  day  temperature  windspeed   event
day
2017-01-01 2017-01-01         32.0        6.0    Rain
2017-01-04 2017-01-04          NaN        9.0   Sunny
2017-01-05 2017-01-05         28.0        NaN    Snow
2017-01-06 2017-01-06          NaN        7.0     NaN
2017-01-07 2017-01-07         32.0        NaN    Rain
2017-01-08 2017-01-08          NaN        NaN   Sunny
2017-01-09 2017-01-09          NaN        NaN     NaN
2017-01-10 2017-01-10         34.1        8.1  Cloudy
2017-01-11 2017-01-11         40.0       12.0   Sunny

In [27]:
df.ffill(axis='columns')

,day,temperature,windspeed,event
day,,,,
2017-01-01,2017-01-01 00:00:00,32.0,6.0,Rain
2017-01-04,2017-01-04 00:00:00,2017-01-04 00:00:00,9.0,Sunny
2017-01-05,2017-01-05 00:00:00,28.0,28.0,Snow
2017-01-06,2017-01-06 00:00:00,2017-01-06 00:00:00,7.0,7.0
2017-01-07,2017-01-07 00:00:00,32.0,32.0,Rain
2017-01-08,2017-01-08 00:00:00,2017-01-08 00:00:00,2017-01-08 00:00:00,Sunny
2017-01-09,2017-01-09 00:00:00,2017-01-09 00:00:00,2017-01-09 00:00:00,2017-01-09 00:00:00
2017-01-10,2017-01-10 00:00:00,34.1,8.1,Cloudy
2017-01-11,2017-01-11 00:00:00,40.0,12.0,Sunny

In [28]:
df.ffill()

                  day  temperature  windspeed   event
day
2017-01-01 2017-01-01         32.0        6.0    Rain
2017-01-04 2017-01-04         32.0        9.0   Sunny
2017-01-05 2017-01-05         28.0        9.0    Snow
2017-01-06 2017-01-06         28.0        7.0    Snow
2017-01-07 2017-01-07         32.0        7.0    Rain
2017-01-08 2017-01-08         32.0        7.0   Sunny
2017-01-09 2017-01-09         32.0        7.0   Sunny
2017-01-10 2017-01-10         34.1        8.1  Cloudy
2017-01-11 2017-01-11         40.0       12.0   Sunny

In [29]:
df.bfill()

                  day  temperature  windspeed   event
day
2017-01-01 2017-01-01         32.0        6.0    Rain
2017-01-04 2017-01-04         28.0        9.0   Sunny
2017-01-05 2017-01-05         28.0        7.0    Snow
2017-01-06 2017-01-06         32.0        7.0    Rain
2017-01-07 2017-01-07         32.0        8.1    Rain
2017-01-08 2017-01-08         34.1        8.1   Sunny
2017-01-09 2017-01-09         34.1        8.1  Cloudy
2017-01-10 2017-01-10         34.1        8.1  Cloudy
2017-01-11 2017-01-11         40.0       12.0   Sunny

In [30]:
df.ffill(axis="columns")

,day,temperature,windspeed,event
day,,,,
2017-01-01,2017-01-01 00:00:00,32.0,6.0,Rain
2017-01-04,2017-01-04 00:00:00,2017-01-04 00:00:00,9.0,Sunny
2017-01-05,2017-01-05 00:00:00,28.0,28.0,Snow
2017-01-06,2017-01-06 00:00:00,2017-01-06 00:00:00,7.0,7.0
2017-01-07,2017-01-07 00:00:00,32.0,32.0,Rain
2017-01-08,2017-01-08 00:00:00,2017-01-08 00:00:00,2017-01-08 00:00:00,Sunny
2017-01-09,2017-01-09 00:00:00,2017-01-09 00:00:00,2017-01-09 00:00:00,2017-01-09 00:00:00
2017-01-10,2017-01-10 00:00:00,34.1,8.1,Cloudy
2017-01-11,2017-01-11 00:00:00,40.0,12.0,Sunny

In [31]:
df.ffill(axis="columns", limit=1)

                            day          temperature windspeed   event
day
2017-01-01  2017-01-01 00:00:00                 32.0       6.0    Rain
2017-01-04  2017-01-04 00:00:00  2017-01-04 00:00:00       9.0   Sunny
2017-01-05  2017-01-05 00:00:00                 28.0      28.0    Snow
2017-01-06  2017-01-06 00:00:00  2017-01-06 00:00:00       7.0     7.0
2017-01-07  2017-01-07 00:00:00                 32.0      32.0    Rain
2017-01-08  2017-01-08 00:00:00  2017-01-08 00:00:00       NaN   Sunny
2017-01-09  2017-01-09 00:00:00  2017-01-09 00:00:00       NaN     NaN
2017-01-10  2017-01-10 00:00:00                 34.1       8.1  Cloudy
2017-01-11  2017-01-11 00:00:00                 40.0      12.0   Sunny

In [37]:
df.dtypes

day            datetime64[us]
temperature           float64
windspeed             float64
event                     str
dtype: object

In [38]:
print(pd.__version__)

3.0.3

In [39]:
numeric_cols = df.select_dtypes(include="number").columns
df[numeric_cols] = df[numeric_cols].interpolate()

In [40]:
df

                  day  temperature  windspeed   event
day
2017-01-01 2017-01-01         32.0      6.000    Rain
2017-01-04 2017-01-04         30.0      9.000   Sunny
2017-01-05 2017-01-05         28.0      8.000    Snow
2017-01-06 2017-01-06         30.0      7.000     NaN
2017-01-07 2017-01-07         32.0      7.275    Rain
2017-01-08 2017-01-08         32.7      7.550   Sunny
2017-01-09 2017-01-09         33.4      7.825     NaN
2017-01-10 2017-01-10         34.1      8.100  Cloudy
2017-01-11 2017-01-11         40.0     12.000   Sunny

In [41]:
df

                  day  temperature  windspeed   event
day
2017-01-01 2017-01-01         32.0      6.000    Rain
2017-01-04 2017-01-04         30.0      9.000   Sunny
2017-01-05 2017-01-05         28.0      8.000    Snow
2017-01-06 2017-01-06         30.0      7.000     NaN
2017-01-07 2017-01-07         32.0      7.275    Rain
2017-01-08 2017-01-08         32.7      7.550   Sunny
2017-01-09 2017-01-09         33.4      7.825     NaN
2017-01-10 2017-01-10         34.1      8.100  Cloudy
2017-01-11 2017-01-11         40.0     12.000   Sunny

In [44]:
df

                  day  temperature  windspeed   event
day
2017-01-01 2017-01-01         32.0        6.0    Rain
2017-01-04 2017-01-04          NaN        9.0   Sunny
2017-01-05 2017-01-05         28.0        NaN    Snow
2017-01-06 2017-01-06          NaN        7.0     NaN
2017-01-07 2017-01-07         32.0        NaN    Rain
2017-01-08 2017-01-08          NaN        NaN   Sunny
2017-01-09 2017-01-09          NaN        NaN     NaN
2017-01-10 2017-01-10         34.1        8.1  Cloudy
2017-01-11 2017-01-11         40.0       12.0   Sunny

In [45]:
df.dropna()

                  day  temperature  windspeed   event
day
2017-01-01 2017-01-01         32.0        6.0    Rain
2017-01-10 2017-01-10         34.1        8.1  Cloudy
2017-01-11 2017-01-11         40.0       12.0   Sunny

In [46]:
df.dropna(how="all")

                  day  temperature  windspeed   event
day
2017-01-01 2017-01-01         32.0        6.0    Rain
2017-01-04 2017-01-04          NaN        9.0   Sunny
2017-01-05 2017-01-05         28.0        NaN    Snow
2017-01-06 2017-01-06          NaN        7.0     NaN
2017-01-07 2017-01-07         32.0        NaN    Rain
2017-01-08 2017-01-08          NaN        NaN   Sunny
2017-01-09 2017-01-09          NaN        NaN     NaN
2017-01-10 2017-01-10         34.1        8.1  Cloudy
2017-01-11 2017-01-11         40.0       12.0   Sunny

In [47]:
df.dropna(how="any")

                  day  temperature  windspeed   event
day
2017-01-01 2017-01-01         32.0        6.0    Rain
2017-01-10 2017-01-10         34.1        8.1  Cloudy
2017-01-11 2017-01-11         40.0       12.0   Sunny

In [51]:
df.dropna(thresh=1)

                  day  temperature  windspeed   event
day
2017-01-01 2017-01-01         32.0        6.0    Rain
2017-01-04 2017-01-04          NaN        9.0   Sunny
2017-01-05 2017-01-05         28.0        NaN    Snow
2017-01-06 2017-01-06          NaN        7.0     NaN
2017-01-07 2017-01-07         32.0        NaN    Rain
2017-01-08 2017-01-08          NaN        NaN   Sunny
2017-01-09 2017-01-09          NaN        NaN     NaN
2017-01-10 2017-01-10         34.1        8.1  Cloudy
2017-01-11 2017-01-11         40.0       12.0   Sunny